### PR TITLE
Refresh project.

### PR DESCRIPTION
**Pull request by dashed**
Refreshing project on top of commits at PR from https://github.com/dashed/shallowequal/pull/6

----

- Revert the 'meat' of shallowequal. I'd like to avoid old-style JS. The 'meat' largely mirrors: https://github.com/facebook/fbjs/blob/b00c419adcf89950a76d5fc119fa152e6902dbab/packages/fbjs/src/core/shallowEqual.js

- Drop lodash dep. Already done at https://github.com/dashed/shallowequal/pull/6

- `Object.keys` will be used in favour of `lodash.keys`. **Rationale:** users consuming the module may use polyfills (e.g. https://github.com/zloirock/core-js) when their projects need it. It shouldn't be the module's responsibility to provide this.

- Remove build step (e.g. rollup or babel). **Rationale:** want to avoid adding unnecessary amounts of boilerplate code that may unintentionally be added. 

- The module will be targeted for users of node v4+, which afaik, has ES6 support. So there is no need for a build step. 

- These changes will be released in `v1.0.0`.

### CODE REVIEW

**Comment by gajus** [comment]
@dashed any reason this was not rolled out?

**Comment by dashed** [comment]
@gajus got sidetracked 😅 

I did few more maintenance commits; will roll out soon. 👍

**Comment by dashed** [comment]
@gajus published `v1.0.0`. Let me know if there are any issues.

**Comment by gajus** [comment]
Thank you

**Comment by gajus** [comment]
@dashed Is there a reason for releasing this as a v1?

This will make it really hard to propagate the update.

**Comment by dashed** [comment]
@gajus I think there were sufficient changes between this PR and `v0.2.2` to warrant releasing this as v1. Especially for change in supported node.js version (node.js v4+). 

The previous version of shallowequal, `v0.2.2`, was published sometime around August 2015. At the time, node.js was io.js (see: https://nodejs.org/en/download/releases/).


-------

Unfortunatlely, this means the shallowequal dep will have to be updated downstream.

**Pull request merged**
