### PR TITLE
Remove node 6 from matrix and reenable engine checks

### PR DESCRIPTION
**Pull request by mcataford**
Completes work from #55 and #52.

Node v6 was marked as no longer supported by a downstream dependency, removing it from the build matrix also removes it from official support for this project, and negates the need for the `--ignore-engines` flag when executing `yarn install`.

### CODE REVIEW

**Comment by mcataford** [comment]
@dashed Figured I'd close the loop since you opened an issue to remove v6 and that ignoring engine checks isn't very desirable.

**Comment by dashed** [comment]
@mcataford awesome stuff! Thanks again 😄 

I'll leave this PR open until sometime April 2019 when node v6 reaches EOL status 👍

**Comment by mcataford** [comment]
:+1: Unless your CI changes a lot, it should age well.

**Comment by dashed** [comment]
@mcataford I've rebased your PR against `master`. I'm going to merge before April ends. 

Thank you for contributing 👏 !

**Pull request merged**
